# Site settings
title: Radio Nope
email: hello@radionope.com
description: > # this means to ignore newlines until "baseurl:"
  NOPE is the supreme alliance of radio. NOPE plays all your future favorite bands. NOPE will make you laugh when the world is woe. NOPE is all you need.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://radionope.com" # the base hostname & protocol for your site
twitter_username: radionope
# github_username:

# Build settings
markdown: kramdown

collections:
  people:
    output: true
  shows:
    output: true

defaults:
  - scope:
      path: ""
      type: people
    values:
      layout: detail-page
      type: people
  - scope:
      path: ""
      type: shows
    values:
      layout: detail-page
      type: shows
